import { submissions } from "./submissions";
export const competitions = [
  {
    id: 1,
    title: "Logo Design",
    subtitle: "Netflix",
    description: "Design the perfect logo for Netflix",
    participants: 42,
    prize: 15000,
    submissions: submissions,
    date: "12 FEB, 2023",
    duration: "10 DAYS",

    lost: false,
    won: true,
  },
  {
    id: 2,
    title: "Illustration",
    subtitle: "Microsoft",
    description: "Create an illustration that captures the essence of Microsoft",
    participants: 56,
    submissions: submissions,

    prize: 25000,
    date: "30 MAR, 2023",
    duration: "11 DAYS",
    lost: false,
    won: false,
  },
  {
    id: 3,
    title: "Animation",
    subtitle: "OpenAI",
    description: "Create an animated short showcasing the potential of OpenAI's technology",
    participants: 23,
    submissions: submissions,

    prize: 14000,
    date: "2 MAR, 2023",
    duration: "14 DAYS",
    lost: false,
    won: false,
  },
  {
    id: 4,
    title: "Graphic Design",
    subtitle: "Meta",
    description: "Design a graphic that represents the future of augmented and virtual reality",
    participants: 36,
    submissions: submissions,

    prize: 12000,
    date: "3 APR, 2023",
    duration: "17 DAYS",
    lost: false,
    won: false,
  },
  {
    id: 5,
    title: "UI/UX Design",
    subtitle: "Google",
    description: "Design a user interface for a new Google product",
    participants: 40,
    prize: 30000,
    submissions: submissions,

    date: "14 MAR, 2023",
    duration: "16 DAYS",
    lost: false,
    won: false,
  },
  {
    id: 6,
    title: "Photography",
    subtitle: "Apple",
    description: "Submit your best photos taken on an Apple device",
    participants: 12,
    prize: 7000,
    submissions: submissions,

    date: "15 MAR, 2023",
    duration: "19 DAYS",
    lost: false,
    won: false,
  },
];

export const competitionHistory = [
  {
    id: 7,
    title: "Web Development",
    subtitle: "Amazon",
    description: "Develop a new feature for Amazon's website. The winner will be hired full-time.",
    participants: 20,
    prize: 2500,
    date: "28 FEB",
    image: "https://i.imgur.com/3ZQ3Z9M.png",
    lost: true,
    won: false,
  },
  {
    id: 8,
    title: "Mobile App Development",
    subtitle: "Facebook",
    description: "Develop a new feature for Facebook's mobile app",
    participants: 22,
    prize: 10000,
    date: "19 MAR, 2023",
    duration: "10 DAYS",
    lost: true,
    won: false,
  },
  {
    id: 9,
    title: "Content Writing",
    subtitle: "Uber",
    description: "Write an article about the future of transportation with Uber",
    participants: 13,
    prize: 2600,
    date: "3 APR, 2023",
    duration: "10 DAYS",
    lost: false,
    won: true,
  },
];
export const wonCompetitions = [
  {
    id: 1,
    title: "Logo Design",
    subtitle: "Netflix",
    description: "Design the perfect logo for Netflix",
    participants: 42,
    prize: 15000,
    date: "12 FEB",
    lost: false,
    won: true,
  },
  {
    id: 9,
    title: "Content Writing",
    subtitle: "Uber",
    description: "Write an article about the future of transportation with Uber",
    participants: 13,
    prize: 2600,
    date: "3 APR",
    image: "https://i.imgur.com/3ZQ3Z9M.png",
    lost: false,
    won: true,
  },
  {
    id: 10,
    title: "Logo Design",
    subtitle: "Google",
    description: "Design the perfect logo for Google",
    participants: 42,
    prize: 15000,

    date: "3 APR, 2023",
    duration: "10 DAYS",

    lost: false,
    won: true,
  },
];
