export const competitions = [
  {
    title: "Logo Design",
    subtitle: "Netflix",
    description: "Design the perfect logo for Netflix",
    participants: 42,
    prize: 15000,
    date: "12 FEB",
    lost: false,
    won: true,
  },
  {
    title: "Illustration",
    subtitle: "Microsoft",
    description: "Create an illustration that captures the essence of Microsoft",
    participants: 56,
    prize: 25000,
    date: "30 MAR",
    lost: false,
    won: false,
  },
  {
    title: "Animation",
    subtitle: "OpenAI",
    description: "Create an animated short showcasing the potential of OpenAI's technology",
    participants: 23,
    prize: 14000,
    date: "2 MAR",
    lost: false,
    won: false,
  },
  {
    title: "Graphic Design",
    subtitle: "Meta",
    description: "Design a graphic that represents the future of augmented and virtual reality",
    participants: 36,
    prize: 12000,
    date: "3 APR",
    lost: false,
    won: false,
  },
  {
    title: "UI/UX Design",
    subtitle: "Google",
    description: "Design a user interface for a new Google product",
    participants: 40,
    prize: 30000,
    date: "14 MAR",
    lost: false,
    won: false,
  },
  {
    title: "Photography",
    subtitle: "Apple",
    description: "Submit your best photos taken on an Apple device",
    participants: 12,
    prize: 7000,
    date: "15 MAR",
    lost: false,
    won: false,
  },
];

export const competitionHistory = [
  {
    title: "Web Development",
    subtitle: "Amazon",
    description: "Develop a new feature for Amazon's website",
    participants: 20,
    prize: 2500,
    date: "28 FEB",
    lost: true,
    won: false,
  },
  {
    title: "Mobile App Development",
    subtitle: "Facebook",
    description: "Develop a new feature for Facebook's mobile app",
    participants: 22,
    prize: 10000,
    date: "19 MAR",
    lost: true,
    won: false,
  },
  {
    title: "Content Writing",
    subtitle: "Uber",
    description: "Write an article about the future of transportation with Uber",
    participants: 13,
    prize: 2600,
    date: "3 APR",
    lost: false,
    won: true,
  },
];
